/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas_1.Admin;

import java.awt.BorderLayout;

/**
 *
 * @author 58424
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
        
        AdminBienvenida b = new AdminBienvenida();
        b.setSize(580,320);
        b.setLocation(0,0);
        
        FondoBlanco.removeAll();
        FondoBlanco.add(b,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        ColumnaVerde = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ConsultarLabel = new javax.swing.JLabel();
        jLabelnOMBREeMPRESA = new javax.swing.JLabel();
        IconoEliminar = new javax.swing.JLabel();
        IconoAgregar = new javax.swing.JLabel();
        IconoConsultar = new javax.swing.JLabel();
        IconoAgregar2 = new javax.swing.JLabel();
        HomeLabel = new javax.swing.JLabel();
        AgregarLabel = new javax.swing.JLabel();
        EliminarLabel = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JButton();
        BtnHome1 = new javax.swing.JButton();
        BtnConsultar1 = new javax.swing.JButton();
        BtnAgregar1 = new javax.swing.JButton();
        Morado = new javax.swing.JPanel();
        Morado3 = new javax.swing.JPanel();
        Morado4 = new javax.swing.JPanel();
        Morado5 = new javax.swing.JPanel();
        FilaVerde = new javax.swing.JPanel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelBienvenidaAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FondoBlancoLayout = new javax.swing.GroupLayout(FondoBlanco);
        FondoBlanco.setLayout(FondoBlancoLayout);
        FondoBlancoLayout.setHorizontalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        FondoBlancoLayout.setVerticalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 580, 320));

        ColumnaVerde.setBackground(new java.awt.Color(54, 33, 83));
        ColumnaVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ColumnaVerde.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        ConsultarLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ConsultarLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarLabel.setText("CONSULTAR");
        ColumnaVerde.add(ConsultarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jLabelnOMBREeMPRESA.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelnOMBREeMPRESA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnOMBREeMPRESA.setText("GESTOR RESIDUOS");
        ColumnaVerde.add(jLabelnOMBREeMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        IconoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen13.png"))); // NOI18N
        ColumnaVerde.add(IconoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        IconoAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2_1.png"))); // NOI18N
        ColumnaVerde.add(IconoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        IconoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen5.png"))); // NOI18N
        ColumnaVerde.add(IconoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 40, 30));

        IconoAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.png"))); // NOI18N
        ColumnaVerde.add(IconoAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        HomeLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeLabel.setText("HOME");
        ColumnaVerde.add(HomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 30));

        AgregarLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgregarLabel.setText("AGREGAR");
        ColumnaVerde.add(AgregarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, -1));

        EliminarLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        EliminarLabel.setForeground(new java.awt.Color(255, 255, 255));
        EliminarLabel.setText("ELIMINAR");
        ColumnaVerde.add(EliminarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 20));

        BtnEliminar.setBackground(new java.awt.Color(85, 55, 118));
        BtnEliminar.setBorder(null);
        BtnEliminar.setBorderPainted(false);
        BtnEliminar.setContentAreaFilled(false);
        BtnEliminar.setFocusPainted(false);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        ColumnaVerde.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 50));

        BtnHome1.setBackground(new java.awt.Color(85, 55, 118));
        BtnHome1.setBorder(null);
        BtnHome1.setBorderPainted(false);
        BtnHome1.setContentAreaFilled(false);
        BtnHome1.setFocusPainted(false);
        BtnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHome1ActionPerformed(evt);
            }
        });
        ColumnaVerde.add(BtnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 50));

        BtnConsultar1.setBackground(new java.awt.Color(85, 55, 118));
        BtnConsultar1.setBorder(null);
        BtnConsultar1.setBorderPainted(false);
        BtnConsultar1.setContentAreaFilled(false);
        BtnConsultar1.setFocusPainted(false);
        BtnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultar1ActionPerformed(evt);
            }
        });
        ColumnaVerde.add(BtnConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 50));

        BtnAgregar1.setBackground(new java.awt.Color(85, 55, 118));
        BtnAgregar1.setBorder(null);
        BtnAgregar1.setBorderPainted(false);
        BtnAgregar1.setContentAreaFilled(false);
        BtnAgregar1.setFocusPainted(false);
        BtnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregar1ActionPerformed(evt);
            }
        });
        ColumnaVerde.add(BtnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 50));

        Morado.setBackground(new java.awt.Color(85, 55, 118));

        javax.swing.GroupLayout MoradoLayout = new javax.swing.GroupLayout(Morado);
        Morado.setLayout(MoradoLayout);
        MoradoLayout.setHorizontalGroup(
            MoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        MoradoLayout.setVerticalGroup(
            MoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ColumnaVerde.add(Morado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        Morado3.setBackground(new java.awt.Color(63, 43, 100));

        javax.swing.GroupLayout Morado3Layout = new javax.swing.GroupLayout(Morado3);
        Morado3.setLayout(Morado3Layout);
        Morado3Layout.setHorizontalGroup(
            Morado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Morado3Layout.setVerticalGroup(
            Morado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ColumnaVerde.add(Morado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        Morado4.setBackground(new java.awt.Color(63, 43, 100));

        javax.swing.GroupLayout Morado4Layout = new javax.swing.GroupLayout(Morado4);
        Morado4.setLayout(Morado4Layout);
        Morado4Layout.setHorizontalGroup(
            Morado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Morado4Layout.setVerticalGroup(
            Morado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ColumnaVerde.add(Morado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        Morado5.setBackground(new java.awt.Color(63, 43, 100));

        javax.swing.GroupLayout Morado5Layout = new javax.swing.GroupLayout(Morado5);
        Morado5.setLayout(Morado5Layout);
        Morado5Layout.setHorizontalGroup(
            Morado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Morado5Layout.setVerticalGroup(
            Morado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ColumnaVerde.add(Morado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        getContentPane().add(ColumnaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 450));

        FilaVerde.setBackground(new java.awt.Color(122, 72, 221));

        jLabelAdministrador.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelAdministrador.setText("Administrador/Admin");

        jLabelBienvenidaAdmin.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelBienvenidaAdmin.setText("Bienvenido a nuestro Gestor de Residuos");

        javax.swing.GroupLayout FilaVerdeLayout = new javax.swing.GroupLayout(FilaVerde);
        FilaVerde.setLayout(FilaVerdeLayout);
        FilaVerdeLayout.setHorizontalGroup(
            FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilaVerdeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBienvenidaAdmin))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        FilaVerdeLayout.setVerticalGroup(
            FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilaVerdeLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabelBienvenidaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdministrador)
                .addGap(32, 32, 32))
        );

        getContentPane().add(FilaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 580, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregar1ActionPerformed
        
    AdminOpcionesAgregar opc = new AdminOpcionesAgregar();
    opc.setSize(580,320);
    
        FondoBlanco.removeAll();
        FondoBlanco.add(opc,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint(); 
        
    }//GEN-LAST:event_BtnAgregar1ActionPerformed

    private void BtnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultar1ActionPerformed
    
        AdminOpcionesConsultar opc = new AdminOpcionesConsultar();
         opc.setSize(580,320);
    
        FondoBlanco.removeAll();
        FondoBlanco.add(opc,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint(); 
    }//GEN-LAST:event_BtnConsultar1ActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
         AdminOpcionesEliminar opc = new AdminOpcionesEliminar();
         opc.setSize(580,320);
    
        FondoBlanco.removeAll();
        FondoBlanco.add(opc,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();  
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHome1ActionPerformed
        AdminBienvenida b = new AdminBienvenida();
        b.setSize(580,320);
        b.setLocation(0,0);
        
        FondoBlanco.removeAll();
        FondoBlanco.add(b,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarLabel;
    private javax.swing.JButton BtnAgregar1;
    private javax.swing.JButton BtnConsultar1;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnHome1;
    private javax.swing.JPanel ColumnaVerde;
    private javax.swing.JLabel ConsultarLabel;
    private javax.swing.JLabel EliminarLabel;
    private javax.swing.JPanel FilaVerde;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel IconoAgregar;
    private javax.swing.JLabel IconoAgregar2;
    private javax.swing.JLabel IconoConsultar;
    private javax.swing.JLabel IconoEliminar;
    private javax.swing.JPanel Morado;
    private javax.swing.JPanel Morado3;
    private javax.swing.JPanel Morado4;
    private javax.swing.JPanel Morado5;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelBienvenidaAdmin;
    private javax.swing.JLabel jLabelnOMBREeMPRESA;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
