/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas_1.Admin;

/**
 *
 * @author 58424
 */
public class AdminBienvenida extends javax.swing.JPanel {

    /**
     * Creates new form AdminBienvenida1
     */
    public AdminBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(560, 260));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setMinimumSize(new java.awt.Dimension(560, 260));
        FondoBlanco.setPreferredSize(new java.awt.Dimension(560, 260));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel1.setText("Este sistema gestor de residuos le permitirá un mayor control con respecto a la administración de los ");
        FondoBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 540, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel3.setText("Usted ha ingresado como adminstrador, por lo tanto podra consultar, agregar y elimiinar la información ");
        FondoBlanco.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 550, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel4.setText("transportistas, del residuo, productores y demás");
        FondoBlanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel5.setText("productores, empresas transportistas y medios de transporte requeridos para el procesamiento de los ");
        FondoBlanco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 540, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("desechos generados en la ciudad.");
        FondoBlanco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 460, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel7.setText("la información que se encuentre en la base de datos. Ademas podra acceder a la información de los");
        FondoBlanco.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 490, -1));

        add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 310));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
