/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas_1.Admin;

import ventanas_1.Admin.AdminEliminar_Destino;
import ventanas_1.Admin.AdminEliminar_Productor;
import ventanas_1.Admin.AdminEliminar_Empresa;
import java.awt.BorderLayout;

/**
 *
 * @author 58424
 */
public class AdminOpcionesEliminar extends javax.swing.JPanel {

    /**
     * Creates new form AdminOpciones_Agregar
     */
    public AdminOpcionesEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PanelMoradoTraslado = new javax.swing.JPanel();
        BtnInfoTraslado = new javax.swing.JButton();
        PanelMoradoProductor = new javax.swing.JPanel();
        BtnInfoProductor1 = new javax.swing.JButton();
        PanelMoradoDestino = new javax.swing.JPanel();
        BtnInfoDestino = new javax.swing.JButton();
        BtnInfoDestino1 = new javax.swing.JButton();
        PanelMoradoTransporte = new javax.swing.JPanel();
        BtnInfoEmpresa = new javax.swing.JButton();
        PanelMoradoResiduos = new javax.swing.JPanel();
        BtnInfoResiduos = new javax.swing.JButton();

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setMinimumSize(new java.awt.Dimension(760, 390));

        jLabel4.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel4.setText("Se encuentra en el panel de eliminar. Seleccione la consulta que ");

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel1.setText("quiere realizar:");

        PanelMoradoTraslado.setBackground(new java.awt.Color(63, 43, 100));

        BtnInfoTraslado.setBackground(new java.awt.Color(63, 43, 100));
        BtnInfoTraslado.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        BtnInfoTraslado.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfoTraslado.setText("Información del Traslado");
        BtnInfoTraslado.setBorder(null);
        BtnInfoTraslado.setBorderPainted(false);
        BtnInfoTraslado.setContentAreaFilled(false);
        BtnInfoTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoTrasladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMoradoTrasladoLayout = new javax.swing.GroupLayout(PanelMoradoTraslado);
        PanelMoradoTraslado.setLayout(PanelMoradoTrasladoLayout);
        PanelMoradoTrasladoLayout.setHorizontalGroup(
            PanelMoradoTrasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoradoTrasladoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnInfoTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMoradoTrasladoLayout.setVerticalGroup(
            PanelMoradoTrasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoradoTrasladoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnInfoTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMoradoProductor.setBackground(new java.awt.Color(63, 43, 100));

        BtnInfoProductor1.setBackground(new java.awt.Color(63, 43, 100));
        BtnInfoProductor1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        BtnInfoProductor1.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfoProductor1.setText("Información del Productor");
        BtnInfoProductor1.setBorder(null);
        BtnInfoProductor1.setBorderPainted(false);
        BtnInfoProductor1.setContentAreaFilled(false);
        BtnInfoProductor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoProductor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMoradoProductorLayout = new javax.swing.GroupLayout(PanelMoradoProductor);
        PanelMoradoProductor.setLayout(PanelMoradoProductorLayout);
        PanelMoradoProductorLayout.setHorizontalGroup(
            PanelMoradoProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoradoProductorLayout.createSequentialGroup()
                .addComponent(BtnInfoProductor1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelMoradoProductorLayout.setVerticalGroup(
            PanelMoradoProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoradoProductorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnInfoProductor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMoradoDestino.setBackground(new java.awt.Color(63, 43, 100));

        BtnInfoDestino.setBackground(new java.awt.Color(63, 43, 100));
        BtnInfoDestino.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        BtnInfoDestino.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfoDestino.setText("Información del Destino");
        BtnInfoDestino.setBorder(null);
        BtnInfoDestino.setBorderPainted(false);
        BtnInfoDestino.setContentAreaFilled(false);
        BtnInfoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMoradoDestinoLayout = new javax.swing.GroupLayout(PanelMoradoDestino);
        PanelMoradoDestino.setLayout(PanelMoradoDestinoLayout);
        PanelMoradoDestinoLayout.setHorizontalGroup(
            PanelMoradoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoradoDestinoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnInfoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelMoradoDestinoLayout.setVerticalGroup(
            PanelMoradoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoradoDestinoLayout.createSequentialGroup()
                .addComponent(BtnInfoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BtnInfoDestino1.setBackground(new java.awt.Color(63, 43, 100));
        BtnInfoDestino1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        BtnInfoDestino1.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfoDestino1.setText("Información del Destino");
        BtnInfoDestino1.setBorder(null);
        BtnInfoDestino1.setBorderPainted(false);
        BtnInfoDestino1.setContentAreaFilled(false);
        BtnInfoDestino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoDestino1ActionPerformed(evt);
            }
        });

        PanelMoradoTransporte.setBackground(new java.awt.Color(63, 43, 100));

        BtnInfoEmpresa.setBackground(new java.awt.Color(63, 43, 100));
        BtnInfoEmpresa.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        BtnInfoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfoEmpresa.setText("Información de las Empresas de Transporte");
        BtnInfoEmpresa.setBorder(null);
        BtnInfoEmpresa.setBorderPainted(false);
        BtnInfoEmpresa.setContentAreaFilled(false);
        BtnInfoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMoradoTransporteLayout = new javax.swing.GroupLayout(PanelMoradoTransporte);
        PanelMoradoTransporte.setLayout(PanelMoradoTransporteLayout);
        PanelMoradoTransporteLayout.setHorizontalGroup(
            PanelMoradoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoradoTransporteLayout.createSequentialGroup()
                .addComponent(BtnInfoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        PanelMoradoTransporteLayout.setVerticalGroup(
            PanelMoradoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoradoTransporteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnInfoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMoradoResiduos.setBackground(new java.awt.Color(63, 43, 100));

        BtnInfoResiduos.setBackground(new java.awt.Color(63, 43, 100));
        BtnInfoResiduos.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        BtnInfoResiduos.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfoResiduos.setText("Información de los Residuos");
        BtnInfoResiduos.setBorder(null);
        BtnInfoResiduos.setBorderPainted(false);
        BtnInfoResiduos.setContentAreaFilled(false);
        BtnInfoResiduos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoResiduosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMoradoResiduosLayout = new javax.swing.GroupLayout(PanelMoradoResiduos);
        PanelMoradoResiduos.setLayout(PanelMoradoResiduosLayout);
        PanelMoradoResiduosLayout.setHorizontalGroup(
            PanelMoradoResiduosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoradoResiduosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnInfoResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelMoradoResiduosLayout.setVerticalGroup(
            PanelMoradoResiduosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMoradoResiduosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnInfoResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout FondoBlancoLayout = new javax.swing.GroupLayout(FondoBlanco);
        FondoBlanco.setLayout(FondoBlancoLayout);
        FondoBlancoLayout.setHorizontalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoBlancoLayout.createSequentialGroup()
                        .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnInfoDestino1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelMoradoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelMoradoResiduos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelMoradoTraslado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelMoradoProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelMoradoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(185, 185, 185))
        );
        FondoBlancoLayout.setVerticalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMoradoProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMoradoTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoBlancoLayout.createSequentialGroup()
                        .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnInfoDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelMoradoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(PanelMoradoResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelMoradoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInfoTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoTrasladoActionPerformed

        AdminEliminar_Traslado con = new AdminEliminar_Traslado();
        con.setSize(560, 260);

        FondoBlanco.removeAll();
        FondoBlanco.add(con,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();
    }//GEN-LAST:event_BtnInfoTrasladoActionPerformed

    private void BtnInfoProductor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoProductor1ActionPerformed
        AdminEliminar_Productor pro = new AdminEliminar_Productor();
        pro.setSize(560, 260);

        FondoBlanco.removeAll();
        FondoBlanco.add(pro,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();
    }//GEN-LAST:event_BtnInfoProductor1ActionPerformed

    private void BtnInfoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInfoDestinoActionPerformed

    private void BtnInfoDestino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoDestino1ActionPerformed
        AdminEliminar_Destino con = new AdminEliminar_Destino();
        con.setSize(560, 260);

        FondoBlanco.removeAll();
        FondoBlanco.add(con,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();
    }//GEN-LAST:event_BtnInfoDestino1ActionPerformed

    private void BtnInfoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoEmpresaActionPerformed
        AdminEliminar_Empresa con = new AdminEliminar_Empresa();
        con.setSize(560, 260);

        FondoBlanco.removeAll();
        FondoBlanco.add(con,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();
    }//GEN-LAST:event_BtnInfoEmpresaActionPerformed

    private void BtnInfoResiduosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoResiduosActionPerformed
        AdminEliminar_Residuo con = new AdminEliminar_Residuo();
        con.setSize(560, 260);

        FondoBlanco.removeAll();
        FondoBlanco.add(con,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint();
    }//GEN-LAST:event_BtnInfoResiduosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInfoDestino;
    private javax.swing.JButton BtnInfoDestino1;
    private javax.swing.JButton BtnInfoEmpresa;
    private javax.swing.JButton BtnInfoProductor1;
    private javax.swing.JButton BtnInfoResiduos;
    private javax.swing.JButton BtnInfoTraslado;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JPanel PanelMoradoDestino;
    private javax.swing.JPanel PanelMoradoProductor;
    private javax.swing.JPanel PanelMoradoResiduos;
    private javax.swing.JPanel PanelMoradoTransporte;
    private javax.swing.JPanel PanelMoradoTraslado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
