/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.Registrar;

import java.awt.BorderLayout;
import ventanas.Admin.AdminOpcionesAgregar;

/**
 *
 * @author 58424
 */
public class Registrar extends javax.swing.JFrame {

    private int yMouse;
    private int xMouse;

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        RegistrarProductor opc = new RegistrarProductor();
        opc.setSize(310,343);
    
        FondoBlanco.removeAll();
        FondoBlanco.add(opc,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoBlanco = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        CREAR_USUARIO = new javax.swing.JLabel();
        EmpresaPanel = new Clases.PanelRound();
        jButton1 = new javax.swing.JButton();
        ProductorPanel = new Clases.PanelRound();
        BtnProductor = new javax.swing.JButton();
        CuadroMorado = new javax.swing.JPanel();
        Gestor = new javax.swing.JLabel();
        Basurateca = new javax.swing.JLabel();
        separadorGestor = new javax.swing.JSeparator();
        Icono = new javax.swing.JLabel();
        SeparadorBasurateca = new javax.swing.JSeparator();
        FondoBlanco = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelFondoBlanco.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        CREAR_USUARIO.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        CREAR_USUARIO.setForeground(new java.awt.Color(0, 0, 0));
        CREAR_USUARIO.setText("Crear usuario");
        jPanelFondoBlanco.add(CREAR_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        EmpresaPanel.setBackground(new java.awt.Color(122, 72, 221));
        EmpresaPanel.setRoundBottomLeft(60);
        EmpresaPanel.setRoundTopLeft(60);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EMPRESA");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmpresaPanelLayout = new javax.swing.GroupLayout(EmpresaPanel);
        EmpresaPanel.setLayout(EmpresaPanelLayout);
        EmpresaPanelLayout.setHorizontalGroup(
            EmpresaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpresaPanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EmpresaPanelLayout.setVerticalGroup(
            EmpresaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelFondoBlanco.add(EmpresaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 40));

        ProductorPanel.setBackground(new java.awt.Color(85, 55, 118));
        ProductorPanel.setRoundBottomRight(60);
        ProductorPanel.setRoundTopRight(60);

        BtnProductor.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        BtnProductor.setForeground(new java.awt.Color(255, 255, 255));
        BtnProductor.setText("Productor");
        BtnProductor.setBorder(null);
        BtnProductor.setContentAreaFilled(false);
        BtnProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductorPanelLayout = new javax.swing.GroupLayout(ProductorPanel);
        ProductorPanel.setLayout(ProductorPanelLayout);
        ProductorPanelLayout.setHorizontalGroup(
            ProductorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnProductor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        ProductorPanelLayout.setVerticalGroup(
            ProductorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnProductor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelFondoBlanco.add(ProductorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));

        getContentPane().add(jPanelFondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 120));

        CuadroMorado.setBackground(new java.awt.Color(63, 43, 100));

        Gestor.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        Gestor.setForeground(new java.awt.Color(255, 255, 255));
        Gestor.setText("GESTOR DE RESIDUOS");

        Basurateca.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        Basurateca.setForeground(new java.awt.Color(255, 255, 255));
        Basurateca.setText("basureteca");

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N

        javax.swing.GroupLayout CuadroMoradoLayout = new javax.swing.GroupLayout(CuadroMorado);
        CuadroMorado.setLayout(CuadroMoradoLayout);
        CuadroMoradoLayout.setHorizontalGroup(
            CuadroMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadroMoradoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CuadroMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroMoradoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(SeparadorBasurateca, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadroMoradoLayout.createSequentialGroup()
                        .addComponent(Basurateca)
                        .addGap(94, 94, 94))))
            .addGroup(CuadroMoradoLayout.createSequentialGroup()
                .addGroup(CuadroMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroMoradoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(CuadroMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuadroMoradoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(separadorGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Gestor)))
                    .addGroup(CuadroMoradoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        CuadroMoradoLayout.setVerticalGroup(
            CuadroMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroMoradoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Icono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Gestor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Basurateca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorBasurateca, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        getContentPane().add(CuadroMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 320, 460));

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FondoBlancoLayout = new javax.swing.GroupLayout(FondoBlanco);
        FondoBlanco.setLayout(FondoBlancoLayout);
        FondoBlancoLayout.setHorizontalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        FondoBlancoLayout.setVerticalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void BtnProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductorActionPerformed
                 RegistrarProductor opc = new RegistrarProductor();
    opc.setSize(310,343);
    
        FondoBlanco.removeAll();
        FondoBlanco.add(opc,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint(); 
    }//GEN-LAST:event_BtnProductorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         RegistrarEmpresa opc = new RegistrarEmpresa();
    opc.setSize(310,343);
    
        FondoBlanco.removeAll();
        FondoBlanco.add(opc,BorderLayout.CENTER);
        FondoBlanco.revalidate();
        FondoBlanco.repaint(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Basurateca;
    private javax.swing.JButton BtnProductor;
    private javax.swing.JLabel CREAR_USUARIO;
    private javax.swing.JPanel CuadroMorado;
    private Clases.PanelRound EmpresaPanel;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel Gestor;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Icono;
    private Clases.PanelRound ProductorPanel;
    private javax.swing.JSeparator SeparadorBasurateca;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelFondoBlanco;
    private javax.swing.JSeparator separadorGestor;
    // End of variables declaration//GEN-END:variables
}
