/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas_1;

/**
 *
 * @author 58424
 */
public class AdminConsultar extends javax.swing.JFrame {

    /**
     * Creates new form AdminConsultar
     */
    public AdminConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        ColumnaMorada = new javax.swing.JPanel();
        jPanelEliminar = new javax.swing.JPanel();
        IconoAgregar3 = new javax.swing.JLabel();
        LabelAgregar3 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        IconoConsultar = new javax.swing.JLabel();
        LabelConsultar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        IconoAgregar2 = new javax.swing.JLabel();
        LabelAgregar2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LabelConsultar1 = new javax.swing.JLabel();
        IconoConsultar1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelnOMBREeMPRESA = new javax.swing.JLabel();
        FilaMorada = new javax.swing.JPanel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelBienvenidaAdmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColumnaMorada.setBackground(new java.awt.Color(54, 33, 83));
        ColumnaMorada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEliminar.setBackground(new java.awt.Color(63, 43, 100));
        jPanelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoAgregar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen4.png"))); // NOI18N
        jPanelEliminar.add(IconoAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        LabelAgregar3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelAgregar3.setForeground(new java.awt.Color(0, 0, 0));
        LabelAgregar3.setText("ELIMINAR");
        jPanelEliminar.add(LabelAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 17, 90, 20));

        ColumnaMorada.add(jPanelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 50));

        jPanelHome.setBackground(new java.awt.Color(85, 55, 118));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen5.png"))); // NOI18N
        jPanelHome.add(IconoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        LabelConsultar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelConsultar.setForeground(new java.awt.Color(0, 0, 0));
        LabelConsultar.setText("HOME");
        jPanelHome.add(LabelConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        ColumnaMorada.add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        jPanel3.setBackground(new java.awt.Color(63, 43, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.png"))); // NOI18N
        jPanel3.add(IconoAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        LabelAgregar2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelAgregar2.setForeground(new java.awt.Color(0, 0, 0));
        LabelAgregar2.setText("AGREGAR");
        jPanel3.add(LabelAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, -1));

        ColumnaMorada.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        jPanel5.setBackground(new java.awt.Color(63, 43, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelConsultar1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelConsultar1.setForeground(new java.awt.Color(0, 0, 0));
        LabelConsultar1.setText("CONSULTAR");
        jPanel5.add(LabelConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, -1));

        IconoConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2_1.png"))); // NOI18N
        jPanel5.add(IconoConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        ColumnaMorada.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));
        ColumnaMorada.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        jLabelnOMBREeMPRESA.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelnOMBREeMPRESA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnOMBREeMPRESA.setText("GESTOR RESIDUOS");
        ColumnaMorada.add(jLabelnOMBREeMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        FondoBlanco.add(ColumnaMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 390));

        FilaMorada.setBackground(new java.awt.Color(122, 72, 221));

        jLabelAdministrador.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabelAdministrador.setText("Administrador/Admin");

        jLabelBienvenidaAdmin.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabelBienvenidaAdmin.setText("Bienvenido a nuestro Gestor de Residuos");

        javax.swing.GroupLayout FilaMoradaLayout = new javax.swing.GroupLayout(FilaMorada);
        FilaMorada.setLayout(FilaMoradaLayout);
        FilaMoradaLayout.setHorizontalGroup(
            FilaMoradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilaMoradaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FilaMoradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBienvenidaAdmin))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        FilaMoradaLayout.setVerticalGroup(
            FilaMoradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilaMoradaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabelBienvenidaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdministrador)
                .addGap(32, 32, 32))
        );

        FondoBlanco.add(FilaMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 520, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel4.setText("Se encuentra en el panel de consultas. Seleccione la consulta que ");
        FondoBlanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 450, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel1.setText("quiere realizar:");
        FondoBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, -1));

        jButton1.setBackground(new java.awt.Color(63, 43, 100));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Información de los Residuos");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        FondoBlanco.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 170, 30));

        jButton2.setBackground(new java.awt.Color(63, 43, 100));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Información de las Empresas de Transporte");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        FondoBlanco.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, 30));

        jButton3.setBackground(new java.awt.Color(63, 43, 100));
        jButton3.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Información del Productor");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        FondoBlanco.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 30));

        jButton4.setBackground(new java.awt.Color(63, 43, 100));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Información del Translado");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        FondoBlanco.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 30));

        jButton5.setBackground(new java.awt.Color(63, 43, 100));
        jButton5.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Información del Destino");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        FondoBlanco.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColumnaMorada;
    private javax.swing.JPanel FilaMorada;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel IconoAgregar2;
    private javax.swing.JLabel IconoAgregar3;
    private javax.swing.JLabel IconoConsultar;
    private javax.swing.JLabel IconoConsultar1;
    private javax.swing.JLabel LabelAgregar2;
    private javax.swing.JLabel LabelAgregar3;
    private javax.swing.JLabel LabelConsultar;
    private javax.swing.JLabel LabelConsultar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelBienvenidaAdmin;
    private javax.swing.JLabel jLabelnOMBREeMPRESA;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
