/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas_1;

/**
 *
 * @author 58424
 */
public class COPIAR_COLORES extends javax.swing.JFrame {

    /**
     * Creates new form COPIAR_COLORES
     */
    public COPIAR_COLORES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ColumnaVerde = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ConsultarLabel = new javax.swing.JLabel();
        jLabelnOMBREeMPRESA = new javax.swing.JLabel();
        IconoEliminar = new javax.swing.JLabel();
        IconoAgregar = new javax.swing.JLabel();
        IconoConsultar = new javax.swing.JLabel();
        IconoAgregar2 = new javax.swing.JLabel();
        HomeLabel = new javax.swing.JLabel();
        AgregarLabel = new javax.swing.JLabel();
        EliminarLabel = new javax.swing.JLabel();
        BtnConsultar = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnAgregar1 = new javax.swing.JButton();
        BtnHome1 = new javax.swing.JButton();
        FilaVerde = new javax.swing.JPanel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelBienvenidaAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel4.setText("Se encuentra en el panel de consultas. Seleccione la consulta que ");
        FondoBlanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 450, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel1.setText("quiere realizar:");
        FondoBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, -1));

        jButton1.setBackground(new java.awt.Color(63, 43, 100));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Información de los Residuos");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        FondoBlanco.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 170, 30));

        jButton2.setBackground(new java.awt.Color(63, 43, 100));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Información de las Empresas de Transporte");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        FondoBlanco.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, 30));

        jButton3.setBackground(new java.awt.Color(63, 43, 100));
        jButton3.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Información del Productor");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        FondoBlanco.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 30));

        jButton4.setBackground(new java.awt.Color(63, 43, 100));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Información del Translado");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        FondoBlanco.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 30));

        jButton5.setBackground(new java.awt.Color(63, 43, 100));
        jButton5.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Información del Destino");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        FondoBlanco.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 30));

        ColumnaVerde.setBackground(new java.awt.Color(54, 33, 83));
        ColumnaVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ColumnaVerde.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        ConsultarLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ConsultarLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarLabel.setText("CONSULTAR");
        ColumnaVerde.add(ConsultarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jLabelnOMBREeMPRESA.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelnOMBREeMPRESA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnOMBREeMPRESA.setText("GESTOR RESIDUOS");
        ColumnaVerde.add(jLabelnOMBREeMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        IconoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen13.png"))); // NOI18N
        ColumnaVerde.add(IconoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        IconoAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2_1.png"))); // NOI18N
        ColumnaVerde.add(IconoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        IconoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen5.png"))); // NOI18N
        ColumnaVerde.add(IconoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 40, 30));

        IconoAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.png"))); // NOI18N
        ColumnaVerde.add(IconoAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        HomeLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeLabel.setText("HOME");
        ColumnaVerde.add(HomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 30));

        AgregarLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgregarLabel.setText("AGREGAR");
        ColumnaVerde.add(AgregarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, -1));

        EliminarLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        EliminarLabel.setForeground(new java.awt.Color(255, 255, 255));
        EliminarLabel.setText("ELIMINAR");
        ColumnaVerde.add(EliminarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 20));

        BtnConsultar.setBackground(new java.awt.Color(63, 43, 100));
        BtnConsultar.setBorder(null);
        BtnConsultar.setBorderPainted(false);
        BtnConsultar.setFocusPainted(false);
        ColumnaVerde.add(BtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        BtnHome.setBackground(new java.awt.Color(85, 55, 118));
        BtnHome.setBorder(null);
        BtnHome.setBorderPainted(false);
        BtnHome.setFocusPainted(false);
        ColumnaVerde.add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 50));

        BtnEliminar.setBackground(new java.awt.Color(63, 43, 100));
        BtnEliminar.setBorder(null);
        BtnEliminar.setBorderPainted(false);
        BtnEliminar.setFocusPainted(false);
        ColumnaVerde.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 50));

        BtnAgregar1.setBackground(new java.awt.Color(63, 43, 100));
        BtnAgregar1.setBorder(null);
        BtnAgregar1.setBorderPainted(false);
        BtnAgregar1.setFocusPainted(false);
        ColumnaVerde.add(BtnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        BtnHome1.setBackground(new java.awt.Color(85, 55, 118));
        BtnHome1.setBorder(null);
        BtnHome1.setBorderPainted(false);
        BtnHome1.setFocusPainted(false);
        ColumnaVerde.add(BtnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        FondoBlanco.add(ColumnaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 390));

        FilaVerde.setBackground(new java.awt.Color(122, 72, 221));

        jLabelAdministrador.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelAdministrador.setText("Administrador/Admin");

        jLabelBienvenidaAdmin.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelBienvenidaAdmin.setText("Bienvenido a nuestro Gestor de Residuos");

        javax.swing.GroupLayout FilaVerdeLayout = new javax.swing.GroupLayout(FilaVerde);
        FilaVerde.setLayout(FilaVerdeLayout);
        FilaVerdeLayout.setHorizontalGroup(
            FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilaVerdeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBienvenidaAdmin))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        FilaVerdeLayout.setVerticalGroup(
            FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilaVerdeLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabelBienvenidaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdministrador)
                .addGap(32, 32, 32))
        );

        FondoBlanco.add(FilaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COPIAR_COLORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COPIAR_COLORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COPIAR_COLORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COPIAR_COLORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COPIAR_COLORES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarLabel;
    private javax.swing.JButton BtnAgregar1;
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnHome1;
    private javax.swing.JPanel ColumnaVerde;
    private javax.swing.JLabel ConsultarLabel;
    private javax.swing.JLabel EliminarLabel;
    private javax.swing.JPanel FilaVerde;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel IconoAgregar;
    private javax.swing.JLabel IconoAgregar2;
    private javax.swing.JLabel IconoConsultar;
    private javax.swing.JLabel IconoEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelBienvenidaAdmin;
    private javax.swing.JLabel jLabelnOMBREeMPRESA;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
