/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas_1;

/**
 *
 * @author 58424
 */
public class OpcionesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasAdmin
     */
    public OpcionesAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        ColumnaVerde = new javax.swing.JPanel();
        jPanelEliminar = new javax.swing.JPanel();
        IconoAgregar3 = new javax.swing.JLabel();
        LabelAgregar3 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        IconoConsultar = new javax.swing.JLabel();
        LabelConsultar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabelAgregar2 = new javax.swing.JLabel();
        IconoConsultar1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LabelConsultar1 = new javax.swing.JLabel();
        IconoAgregar2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelnOMBREeMPRESA = new javax.swing.JLabel();
        FilaVerde = new javax.swing.JPanel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelBienvenidaAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColumnaVerde.setBackground(new java.awt.Color(54, 33, 83));
        ColumnaVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEliminar.setBackground(new java.awt.Color(63, 43, 100));
        jPanelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoAgregar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen4.png"))); // NOI18N
        jPanelEliminar.add(IconoAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        LabelAgregar3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelAgregar3.setForeground(new java.awt.Color(0, 0, 0));
        LabelAgregar3.setText("ELIMINAR");
        jPanelEliminar.add(LabelAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 17, 90, 20));

        ColumnaVerde.add(jPanelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 50));

        jPanelHome.setBackground(new java.awt.Color(85, 55, 118));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen5.png"))); // NOI18N
        jPanelHome.add(IconoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        LabelConsultar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelConsultar.setForeground(new java.awt.Color(0, 0, 0));
        LabelConsultar.setText("HOME");
        jPanelHome.add(LabelConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        ColumnaVerde.add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        jPanel3.setBackground(new java.awt.Color(63, 43, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAgregar2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelAgregar2.setForeground(new java.awt.Color(0, 0, 0));
        LabelAgregar2.setText("AGREGAR");
        jPanel3.add(LabelAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, -1));

        IconoConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2_1.png"))); // NOI18N
        jPanel3.add(IconoConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        ColumnaVerde.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        jPanel5.setBackground(new java.awt.Color(63, 43, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelConsultar1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelConsultar1.setForeground(new java.awt.Color(0, 0, 0));
        LabelConsultar1.setText("CONSULTAR");
        jPanel5.add(LabelConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, -1));

        IconoAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.png"))); // NOI18N
        jPanel5.add(IconoAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        ColumnaVerde.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));
        ColumnaVerde.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        jLabelnOMBREeMPRESA.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelnOMBREeMPRESA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnOMBREeMPRESA.setText("GESTOR RESIDUOS");
        ColumnaVerde.add(jLabelnOMBREeMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        FondoBlanco.add(ColumnaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 390));

        FilaVerde.setBackground(new java.awt.Color(122, 72, 221));

        jLabelAdministrador.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelAdministrador.setText("Administrador/Admin");

        jLabelBienvenidaAdmin.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelBienvenidaAdmin.setText("Bienvenido a nuestro Gestor de Residuos");

        javax.swing.GroupLayout FilaVerdeLayout = new javax.swing.GroupLayout(FilaVerde);
        FilaVerde.setLayout(FilaVerdeLayout);
        FilaVerdeLayout.setHorizontalGroup(
            FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilaVerdeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBienvenidaAdmin))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        FilaVerdeLayout.setVerticalGroup(
            FilaVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilaVerdeLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabelBienvenidaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdministrador)
                .addGap(32, 32, 32))
        );

        FondoBlanco.add(FilaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 570, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel1.setText("Este sistema gestor de residuos le permitirá un mayor control con respecto a la administración de los ");
        FondoBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 540, 10));

        jLabel3.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel3.setText("Usted ha ingresado como adminstrador, por lo tanto podra consultar, agregar y elimiinar la información ");
        FondoBlanco.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 550, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel4.setText("transportistas, del residuo, productores y demás");
        FondoBlanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel5.setText("productores, empresas transportistas y medios de transporte requeridos para el procesamiento de los ");
        FondoBlanco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 540, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("desechos generados en la ciudad.");
        FondoBlanco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 460, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel7.setText("la información que se encuentre en la base de datos. Ademas podra acceder a la información de los");
        FondoBlanco.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 490, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColumnaVerde;
    private javax.swing.JPanel FilaVerde;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel IconoAgregar2;
    private javax.swing.JLabel IconoAgregar3;
    private javax.swing.JLabel IconoConsultar;
    private javax.swing.JLabel IconoConsultar1;
    private javax.swing.JLabel LabelAgregar2;
    private javax.swing.JLabel LabelAgregar3;
    private javax.swing.JLabel LabelConsultar;
    private javax.swing.JLabel LabelConsultar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelBienvenidaAdmin;
    private javax.swing.JLabel jLabelnOMBREeMPRESA;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
